# Generated by Django 5.0.6 on 2025-03-17 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('hall', models.CharField(max_length=3)),
                ('balcony', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=200)),
                ('AC', models.CharField(max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('date_added', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
