# Generated by Django 5.1.7 on 2025-03-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=4500),
            preserve_default=False,
        ),
    ]
