# Generated by Django 5.1.7 on 2025-03-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='cost',
            new_name='rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
    ]
