# Generated by Django 5.1.7 on 2025-03-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
