# Generated by Django 5.1.7 on 2025-03-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_message_is_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_rented',
        ),
        migrations.AddField(
            model_name='property',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
