# Generated by Django 5.1.7 on 2025-03-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_message_is_rented_property_is_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='google_map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
