# Generated by Django 5.1.7 on 2025-03-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_google_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='google_map_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
