# Generated by Django 5.1.7 on 2025-03-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_vr_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='vr_tour',
        ),
        migrations.AddField(
            model_name='property',
            name='vr_image',
            field=models.ImageField(blank=True, null=True, upload_to='vr_images/'),
        ),
    ]
